// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type LoginResp struct {
	Status           string `json:"status"`
	CurrentAuthority string `json:"currentAuthority"`
	UserName         string `json:"userName"`
	AccessToken      string `json:"token"`
	AccessExpire     int64  `json:"accessExpire"`
	RefreshAfter     int64  `json:"refreshAfter"`
}

type AdminRole struct {
	Name string `json:"name"` // 角色名
	Slug string `json:"slug"` // 角色标识
}

type AdminPermission struct {
	Id          int32  `json:"id"`          //
	ParentId    int32  `json:"parent_id"`   // 上级菜单ID
	Name        string `json:"name"`        // 菜单名称
	Icon        string `json:"icon"`        // 菜单图标
	Rule        string `json:"rule"`        // 菜单路径
	Description string `json:"description"` // 菜单描述
}

type UserInfoResp struct {
	Avatar          string             `json:"avatar"`
	Name            string             `json:"name"`
	NickName        string             `json:"nickName"`
	Email           string             `json:"email"`
	Mobile          string             `json:"mobile"`
	CreatedAt       int64              `json:"created_at"`
	AdminRole       []*AdminRole       `json:"admin_role"`
	AdminPermission []*AdminPermission `json:"admin_permission"`
}

type AddUserReq struct {
	Name     string `json:"name"`
	NickName string `json:"nickName"`
	Avatar   string `json:"avatar"`
	Password string `json:"password"`
	Email    string `json:"email,optional"`
	Mobile   string `json:"mobile,optional"`
	Status   int32  `json:"status,optional,default=1,range=[0:1]"`
}

type AddUserResp struct {
}

type DelUserReq struct {
	Id int32 `json:"id"`
}

type DelUserResp struct {
}
