// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go-zero-demo/rpc/models/adminmodel"
)

func newAdminUser(db *gorm.DB, opts ...gen.DOOption) adminUser {
	_adminUser := adminUser{}

	_adminUser.adminUserDo.UseDB(db, opts...)
	_adminUser.adminUserDo.UseModel(&adminmodel.AdminUser{})

	tableName := _adminUser.adminUserDo.TableName()
	_adminUser.ALL = field.NewAsterisk(tableName)
	_adminUser.Id = field.NewInt(tableName, "id")
	_adminUser.Name = field.NewString(tableName, "name")
	_adminUser.NickName = field.NewString(tableName, "nick_name")
	_adminUser.Avatar = field.NewString(tableName, "avatar")
	_adminUser.Password = field.NewString(tableName, "password")
	_adminUser.Email = field.NewString(tableName, "email")
	_adminUser.Mobile = field.NewString(tableName, "mobile")
	_adminUser.Status = field.NewInt(tableName, "status")
	_adminUser.CreateBy = field.NewInt(tableName, "create_by")
	_adminUser.CreatedAt = field.NewTime(tableName, "created_at")
	_adminUser.UpdatedAt = field.NewTime(tableName, "updated_at")
	_adminUser.AdminRole = adminUserManyToManyAdminRole{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("AdminRole", "adminmodel.AdminRole"),
		AdminUser: struct {
			field.RelationField
			AdminRole struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("AdminRole.AdminUser", "adminmodel.AdminUser"),
			AdminRole: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("AdminRole.AdminUser.AdminRole", "adminmodel.AdminRole"),
			},
		},
		AdminPermission: struct {
			field.RelationField
			AdminRole struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("AdminRole.AdminPermission", "adminmodel.AdminPermission"),
			AdminRole: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("AdminRole.AdminPermission.AdminRole", "adminmodel.AdminRole"),
			},
		},
	}

	_adminUser.fillFieldMap()

	return _adminUser
}

type adminUser struct {
	adminUserDo

	ALL       field.Asterisk
	Id        field.Int
	Name      field.String
	NickName  field.String
	Avatar    field.String
	Password  field.String
	Email     field.String
	Mobile    field.String
	Status    field.Int
	CreateBy  field.Int
	CreatedAt field.Time
	UpdatedAt field.Time
	AdminRole adminUserManyToManyAdminRole

	fieldMap map[string]field.Expr
}

func (a adminUser) Table(newTableName string) *adminUser {
	a.adminUserDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a adminUser) As(alias string) *adminUser {
	a.adminUserDo.DO = *(a.adminUserDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *adminUser) updateTableName(table string) *adminUser {
	a.ALL = field.NewAsterisk(table)
	a.Id = field.NewInt(table, "id")
	a.Name = field.NewString(table, "name")
	a.NickName = field.NewString(table, "nick_name")
	a.Avatar = field.NewString(table, "avatar")
	a.Password = field.NewString(table, "password")
	a.Email = field.NewString(table, "email")
	a.Mobile = field.NewString(table, "mobile")
	a.Status = field.NewInt(table, "status")
	a.CreateBy = field.NewInt(table, "create_by")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *adminUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *adminUser) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 12)
	a.fieldMap["id"] = a.Id
	a.fieldMap["name"] = a.Name
	a.fieldMap["nick_name"] = a.NickName
	a.fieldMap["avatar"] = a.Avatar
	a.fieldMap["password"] = a.Password
	a.fieldMap["email"] = a.Email
	a.fieldMap["mobile"] = a.Mobile
	a.fieldMap["status"] = a.Status
	a.fieldMap["create_by"] = a.CreateBy
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt

}

func (a adminUser) clone(db *gorm.DB) adminUser {
	a.adminUserDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a adminUser) replaceDB(db *gorm.DB) adminUser {
	a.adminUserDo.ReplaceDB(db)
	return a
}

type adminUserManyToManyAdminRole struct {
	db *gorm.DB

	field.RelationField

	AdminUser struct {
		field.RelationField
		AdminRole struct {
			field.RelationField
		}
	}
	AdminPermission struct {
		field.RelationField
		AdminRole struct {
			field.RelationField
		}
	}
}

func (a adminUserManyToManyAdminRole) Where(conds ...field.Expr) *adminUserManyToManyAdminRole {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a adminUserManyToManyAdminRole) WithContext(ctx context.Context) *adminUserManyToManyAdminRole {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a adminUserManyToManyAdminRole) Session(session *gorm.Session) *adminUserManyToManyAdminRole {
	a.db = a.db.Session(session)
	return &a
}

func (a adminUserManyToManyAdminRole) Model(m *adminmodel.AdminUser) *adminUserManyToManyAdminRoleTx {
	return &adminUserManyToManyAdminRoleTx{a.db.Model(m).Association(a.Name())}
}

type adminUserManyToManyAdminRoleTx struct{ tx *gorm.Association }

func (a adminUserManyToManyAdminRoleTx) Find() (result []*adminmodel.AdminRole, err error) {
	return result, a.tx.Find(&result)
}

func (a adminUserManyToManyAdminRoleTx) Append(values ...*adminmodel.AdminRole) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a adminUserManyToManyAdminRoleTx) Replace(values ...*adminmodel.AdminRole) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a adminUserManyToManyAdminRoleTx) Delete(values ...*adminmodel.AdminRole) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a adminUserManyToManyAdminRoleTx) Clear() error {
	return a.tx.Clear()
}

func (a adminUserManyToManyAdminRoleTx) Count() int64 {
	return a.tx.Count()
}

type adminUserDo struct{ gen.DO }

type IAdminUserDo interface {
	gen.SubQuery
	Debug() IAdminUserDo
	WithContext(ctx context.Context) IAdminUserDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAdminUserDo
	WriteDB() IAdminUserDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAdminUserDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAdminUserDo
	Not(conds ...gen.Condition) IAdminUserDo
	Or(conds ...gen.Condition) IAdminUserDo
	Select(conds ...field.Expr) IAdminUserDo
	Where(conds ...gen.Condition) IAdminUserDo
	Order(conds ...field.Expr) IAdminUserDo
	Distinct(cols ...field.Expr) IAdminUserDo
	Omit(cols ...field.Expr) IAdminUserDo
	Join(table schema.Tabler, on ...field.Expr) IAdminUserDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAdminUserDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAdminUserDo
	Group(cols ...field.Expr) IAdminUserDo
	Having(conds ...gen.Condition) IAdminUserDo
	Limit(limit int) IAdminUserDo
	Offset(offset int) IAdminUserDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAdminUserDo
	Unscoped() IAdminUserDo
	Create(values ...*adminmodel.AdminUser) error
	CreateInBatches(values []*adminmodel.AdminUser, batchSize int) error
	Save(values ...*adminmodel.AdminUser) error
	First() (*adminmodel.AdminUser, error)
	Take() (*adminmodel.AdminUser, error)
	Last() (*adminmodel.AdminUser, error)
	Find() ([]*adminmodel.AdminUser, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*adminmodel.AdminUser, err error)
	FindInBatches(result *[]*adminmodel.AdminUser, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*adminmodel.AdminUser) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAdminUserDo
	Assign(attrs ...field.AssignExpr) IAdminUserDo
	Joins(fields ...field.RelationField) IAdminUserDo
	Preload(fields ...field.RelationField) IAdminUserDo
	FirstOrInit() (*adminmodel.AdminUser, error)
	FirstOrCreate() (*adminmodel.AdminUser, error)
	FindByPage(offset int, limit int) (result []*adminmodel.AdminUser, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAdminUserDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	FindUserByName(name string) (result *adminmodel.AdminUser, err error)
}

// SELECT * FROM @@table WHERE name = @name
func (a adminUserDo) FindUserByName(name string) (result *adminmodel.AdminUser, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	generateSQL.WriteString("SELECT * FROM admin_users WHERE name = ? ")

	var executeSQL *gorm.DB
	executeSQL = a.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (a adminUserDo) Debug() IAdminUserDo {
	return a.withDO(a.DO.Debug())
}

func (a adminUserDo) WithContext(ctx context.Context) IAdminUserDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a adminUserDo) ReadDB() IAdminUserDo {
	return a.Clauses(dbresolver.Read)
}

func (a adminUserDo) WriteDB() IAdminUserDo {
	return a.Clauses(dbresolver.Write)
}

func (a adminUserDo) Session(config *gorm.Session) IAdminUserDo {
	return a.withDO(a.DO.Session(config))
}

func (a adminUserDo) Clauses(conds ...clause.Expression) IAdminUserDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a adminUserDo) Returning(value interface{}, columns ...string) IAdminUserDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a adminUserDo) Not(conds ...gen.Condition) IAdminUserDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a adminUserDo) Or(conds ...gen.Condition) IAdminUserDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a adminUserDo) Select(conds ...field.Expr) IAdminUserDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a adminUserDo) Where(conds ...gen.Condition) IAdminUserDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a adminUserDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IAdminUserDo {
	return a.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (a adminUserDo) Order(conds ...field.Expr) IAdminUserDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a adminUserDo) Distinct(cols ...field.Expr) IAdminUserDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a adminUserDo) Omit(cols ...field.Expr) IAdminUserDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a adminUserDo) Join(table schema.Tabler, on ...field.Expr) IAdminUserDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a adminUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAdminUserDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a adminUserDo) RightJoin(table schema.Tabler, on ...field.Expr) IAdminUserDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a adminUserDo) Group(cols ...field.Expr) IAdminUserDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a adminUserDo) Having(conds ...gen.Condition) IAdminUserDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a adminUserDo) Limit(limit int) IAdminUserDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a adminUserDo) Offset(offset int) IAdminUserDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a adminUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAdminUserDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a adminUserDo) Unscoped() IAdminUserDo {
	return a.withDO(a.DO.Unscoped())
}

func (a adminUserDo) Create(values ...*adminmodel.AdminUser) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a adminUserDo) CreateInBatches(values []*adminmodel.AdminUser, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a adminUserDo) Save(values ...*adminmodel.AdminUser) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a adminUserDo) First() (*adminmodel.AdminUser, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*adminmodel.AdminUser), nil
	}
}

func (a adminUserDo) Take() (*adminmodel.AdminUser, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*adminmodel.AdminUser), nil
	}
}

func (a adminUserDo) Last() (*adminmodel.AdminUser, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*adminmodel.AdminUser), nil
	}
}

func (a adminUserDo) Find() ([]*adminmodel.AdminUser, error) {
	result, err := a.DO.Find()
	return result.([]*adminmodel.AdminUser), err
}

func (a adminUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*adminmodel.AdminUser, err error) {
	buf := make([]*adminmodel.AdminUser, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a adminUserDo) FindInBatches(result *[]*adminmodel.AdminUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a adminUserDo) Attrs(attrs ...field.AssignExpr) IAdminUserDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a adminUserDo) Assign(attrs ...field.AssignExpr) IAdminUserDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a adminUserDo) Joins(fields ...field.RelationField) IAdminUserDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a adminUserDo) Preload(fields ...field.RelationField) IAdminUserDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a adminUserDo) FirstOrInit() (*adminmodel.AdminUser, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*adminmodel.AdminUser), nil
	}
}

func (a adminUserDo) FirstOrCreate() (*adminmodel.AdminUser, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*adminmodel.AdminUser), nil
	}
}

func (a adminUserDo) FindByPage(offset int, limit int) (result []*adminmodel.AdminUser, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a adminUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a adminUserDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a adminUserDo) Delete(models ...*adminmodel.AdminUser) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *adminUserDo) withDO(do gen.Dao) *adminUserDo {
	a.DO = *do.(*gen.DO)
	return a
}
