// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package sys

import (
	"context"

	"go-zero-demo/rpc/sys/sysclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminPermission     = sysclient.AdminPermission
	AdminRole           = sysclient.AdminRole
	CheckPermissionReq  = sysclient.CheckPermissionReq
	CheckPermissionResp = sysclient.CheckPermissionResp
	InfoReq             = sysclient.InfoReq
	InfoResp            = sysclient.InfoResp
	LoginReq            = sysclient.LoginReq
	LoginResp           = sysclient.LoginResp
	UserAddReq          = sysclient.UserAddReq
	UserAddResp         = sysclient.UserAddResp
	UserDelReq          = sysclient.UserDelReq
	UserDelResp         = sysclient.UserDelResp

	Sys interface {
		CheckPermission(ctx context.Context, in *CheckPermissionReq, opts ...grpc.CallOption) (*CheckPermissionResp, error)
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		UserInfo(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoResp, error)
		AddUser(ctx context.Context, in *UserAddReq, opts ...grpc.CallOption) (*UserAddResp, error)
		DelUser(ctx context.Context, in *UserDelReq, opts ...grpc.CallOption) (*UserDelResp, error)
	}

	defaultSys struct {
		cli zrpc.Client
	}
)

func NewSys(cli zrpc.Client) Sys {
	return &defaultSys{
		cli: cli,
	}
}

func (m *defaultSys) CheckPermission(ctx context.Context, in *CheckPermissionReq, opts ...grpc.CallOption) (*CheckPermissionResp, error) {
	client := sysclient.NewSysClient(m.cli.Conn())
	return client.CheckPermission(ctx, in, opts...)
}

func (m *defaultSys) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := sysclient.NewSysClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultSys) UserInfo(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoResp, error) {
	client := sysclient.NewSysClient(m.cli.Conn())
	return client.UserInfo(ctx, in, opts...)
}

func (m *defaultSys) AddUser(ctx context.Context, in *UserAddReq, opts ...grpc.CallOption) (*UserAddResp, error) {
	client := sysclient.NewSysClient(m.cli.Conn())
	return client.AddUser(ctx, in, opts...)
}

func (m *defaultSys) DelUser(ctx context.Context, in *UserDelReq, opts ...grpc.CallOption) (*UserDelResp, error) {
	client := sysclient.NewSysClient(m.cli.Conn())
	return client.DelUser(ctx, in, opts...)
}
